---
title: "*Coding Smart in Academia* PhD Project"
author: "Flic Anderson"
date: "31/10/2022"
output: 
  ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>

<script>
    $(document).ready(function() {
      $('slide:not(.title-slide, .backdrop, .segue)').append('<footer label=\"CodingSmartInAcademia"></footer>');    
    })
</script>

<style>
  footer:after {
    content: attr(label);
    font-size: 12pt;
    position: absolute;
    bottom: 20px;
    left: 100px;
    line-height: 1.9;
  }
</style>

<style type="text/css">
slides > slide:not(.nobackground):after {
  content: '';
}
</style>

<div class="notes">

Bio: 
Currently a PhD Researcher at EPCC, School of Informatics, at the University of Edinburgh. 
Flic Anderson has been a Research Assistant in Bioinformatics in the Wallace Lab (within the Institute for Cell Biology) at the University of Edinburgh. 
Flic was part of the development team for the 'riboviz' open source software package for processing and analysis of ribosome profiling data, working with colleagues from EPCC (University of Edinburgh) to make the codebase more robust & sustainable.   
With a background in Ecology and Botany (previously a Research Assistant at the Royal Botanic Garden Edinburgh), Flic has worked with a wide range of types of biological data using different software tools and programming languages (particularly R) for the last 8 years, and found herself drawn towards bioinformatics and research software engineering. 
Flic is a member of the Edinburgh Carpentries and a certified Carpentries instructor in foundational coding and data science skills for researchers. 

Title: Coding Smart in Academia: Evidence-Based Software Engineering Approaches for High-Quality Research Software Projects

Abstract:  
This project will investigate which effective software engineering approaches (software engineering techniques and development practices) prevalent in traditional software engineering can be recommended to small research software projects to improve their software quality and development efficiency using empirical evidence from mixed methods approaches and novel software quality measurement frameworks
</div>


## HOW TO (RE-)USE THIS MATERIAL

This is a `.html` presentation created in `R Markdown` with `ioslides`. 

(It's been written in a [.Rmd](http://rmarkdown.rstudio.com) file, and I generated .html slides by 'knitting' it in Rstudio.)

You can check out the code used to make these slides at the [Talk repo](https://github.com/FlicAnderson/PhD10moReview) on Github, and adapt it for your own presentations if you like - there's a MIT Licence on the repo, which means: 

*"Basically, you can do whatever you want as long as you include the original copyright and license notice in any copy of the software/source."*

Source: [tl;drLegal](https://tldrlegal.com/license/mit-license)



# Coding Smart in Academia: *Evidence-Based Software Engineering Approaches for High-Quality Research Software Projects*  



## Outline 

- project question and areas of focus
- project aims & goals 
- main RQs 
- what I've achieved so far 
- project plan / milestones 
- key experiments/studies
- next 6 months priorities 
- challenges for me and the project 

RS: Research software  
SE: Software engineering 



## Project Question

<font size=6>*"Which __effective SE approaches__\* prevalent in traditional SE can be recommended to __small research software projects__ to improve their __software quality__ and __development efficiency__?"* </font>


*Areas of focus:* 

* Software Engineering Approaches in Research Software [SEA]    
* Measuring Research Software [RSM]   
* Research Software Projects [RSP]   

<font size=4>\* Specific __SE techniques__ and more general __SE development practices__. </font>  



## Project Aims

__Aims:__  

* To develop RS __assessment metrics__.  
* To use these in small-scale RS projects to __empirically test__ whether specific SE recommendations are effective and improve RS development. 

__Goals:__   

* Develop __evidence-basis__ to guide future researcher-developers in using effective SE approaches in their RS projects. 
* Feed __SE recommendations back to RS community__ through publications and presentations.



## Main RQs

- "How can effectiveness and appropriateness of SE techniques and development practices in small UK-based RS projects be measured? *[RSM0]*" 

- "Do the identified recommended SE techniques or development practices improve the quality of RS and/or development efficiency if deployed within small RS projects? *[SEA0]*"

- "Which factors influence the adoption and effective use of these recommended SE approaches in small RS projects? *[RSP0]*"



## What I've Achieved so Far   

* __Literature Review__ - broad background reading on research software research, comparisons to software engineering research, some methods studies, and initially focusing on measuring software quality aims   
* Planning and designing *Research Software Testing Experiences Survey*    
* Made start on __ethics process__ for survey experiment and thinking about data management  
* __Networking!__ Researchers, Research Software Community members and software developers / technical leads from industry...     



## What I've Achieved so Far   

* Volunteered at [Sixth Annual Conference for Research Software Engineering](https://rsecon2022.society-rse.org/) (RSECon22)   
* Attended [SSI Collaborations Workshop 2022](https://www.software.ac.uk/cw22) (CW22)  
* Presented at [Edinburgh Open Research Conference 2022](https://edopenresearch.com/edinburghopenresearchconference/)   
* Volunteered at tech industry/ startups conference [Turing Fest 2022](https://www.turingfest.com/conference)    
* Lead-authored /  SSI blog post\* resulting from speed-blog session at CW22  

<font size=4>\* = [Aim for understandability if you want to write good research software](https://www.software.ac.uk/blog/2022-07-04-aim-understandability-if-you-want-write-good-research-software). </font>



## What I've Achieved so Far (Indirect / External)  

* Presented at [Edinburgh Open Research Conference 2022](https://edopenresearch.com/edinburghopenresearchconference/)   
* Demonstrating on *Programming Skills* & *Fundamentals of Data Management* EPCC masters courses   
* Helper \& Demonstrator on [Ed-DaSH](https://edcarp.github.io/Ed-DaSH/) project workshops (Carpentries-style workshops: Data Science for Health and Biosciences)   
* Applied for [SSI Fellowship Programme 2023](https://www.software.ac.uk/programmes-and-events/fellowship-programme) to plan / organise activities relating to improving research software (shortlist confirmed ~Tuesday!)    
* Part of winning team at SSI CollabW22 hack-day :)   



## Project Plan / Milestones 




## Key Experiments / Studies  

__Literature Reviews:__    

 - SE techniques in RS  [SEA0] 
 - RS development practices [SEA0]  
 - RS measurement [RSM0] 
 - RS project factors [RSP0]  


__Studies / Experiments:__   

 - *RS Testing Experiences* survey  [SEA0, RSP0]   
 - *Measuring RS Projects* - develop metrics/framework, then evaluate and refine  [RSM0] 
 - *Evidence-Based RS Interventions* - main experiment, mixed methods [SEA0, RSP0, RSM0]      
 



## Next 6 Months Priorities: 

* Complete ethics procedures, create Data Management Plan  
* Lit Review: SE Approaches (techniques/development practices) [SEA0]   
* Run, analyse and write up RS Testing Experiences Survey [SEA0 / RSP0]   
* Lit Review: RS Measurement [RSM0]  
* Develop (+ test and refine) RS assessment metrics and methods [RSM0]   
* Develop and refine 'recommendation' SE approaches [SEA0]  
* Recruiting RS projects for Interventions study [SEA0 / RSP0]   
* Begin Evidence-Based RS Interventions study [SEA0 / RSP0 / RSM0]   






## Challenges for Me \& The Project

__Collating a list of specific promising SE approaches to recommend in the Interventions study.__   

They need to:     
 - be quickly/easily learned with skill-up materials available    
 - have claims supporting effectiveness in SE  
 - be likely to transfer to RS projects well  
 - address software quality or development efficiency  
 - have differing actions/methods of improvement  
 - result in measurable improvement in (6-9mo) intervention period    


*Mitigations:* 
Collate potential recommendations from lit reviews, survey study feedback, external datasets;  
Gather feedback on RS expectations/experiences of these recommendations re: likely effectiveness. 



## Challenges for Me \& The Project  

__Project timescales are short for measuring changes to codebase and development__ 

Risk of not beginning long forward study Interventions experiment soon enough, delays to data collection, difficulty in arranging interviews/meetings with key developers. 

*Mitigations:* 
Collate list of potential projects which may be likely to meet participation criteria, adding to or subtracting from this as I refine the criteria and verify availability or interest.  
Focus on metrics which are likely to result in measurable changes relatively quickly.  

